- name: Package Installed
  apt: name=collectd state=present

- name: Configured
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
            owner=root group=root mode=644
  notify:
      - restart collectd

- name: Service Running
  service: name=collectd state=started enabled=true
